#!/bin/bash

BUILD_DIR=$(pwd)
OUTPUT_DIR=$BUILD_DIR/output

BUILDROOT=$BUILD_DIR/buildroot
BUILDROOT_EXTERNAL=$BUILD_DIR/br-external

mkdir -p $OUTPUT_DIR
make -C $BUILDROOT O=$OUTPUT_DIR BR2_EXTERNAL=$BUILDROOT_EXTERNAL $@
