version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - service-net
    # volumes:
    #   - /srv/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - service-net
  
  elm_exporter:
    build:
      context: elm327-exporter
      dockerfile: Containerfile
    privileged: true
    restart: always
    networks:
      - service-net
    envrionment:
      - ELM_PORT=/dev/rfcomm0

networks:
  service-net:
