version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - service-net
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - service-net
  
  elm_exporter:
    build:
      context: elm327-exporter
      dockerfile: Containerfile
    privileged: true
    restart: always
    networks:
      - service-net
    environment:
      - ELM_PORT=/dev/rfcomm0

networks:
  service-net:
