version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    networks:
      - service-net
    # volumes:
    #   - /srv/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - service-net

networks:
  service-net:
