version: '3.3'

services:
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 80:9090
    networks:
      - internal
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus-data:/prometheus

  elm_exporter:
    build:
      context: elm327-exporter
      dockerfile: Containerfile
    privileged: true
    restart: always
    networks:
      - internal
    environment:
      - ELM_PORT=/dev/rfcomm0

  dht_exporter:
    build:
      context: dht11-exporter
      dockerfile: Containerfile
    privileged: true
    restart: always
    networks:
      - internal

  alert_indicator:
    build:
      context: alert-indicator
      dockerfile: Containerfile
    privileged: true
    restart: always
    networks:
      - internal
    environment:
      - LED_PIN=21
      - PROMETHEUS_URL=http://prometheus:9090
      - ALERT_NAME=ColdEngine

volumes:
  prometheus-data:

networks:
  internal:
